### ISSUE TITLE
Use formatted strings for URL mapping

### ISSUE THREAD

**Issue by dagwieers** [datacenter/aci-ansible#151]
So looking at the way the URL mapping is constructed, I wonder if it would not be easier if we used formatted strings like:

```python
access_port_block=dict(aci_class='infraPortBlk', dn='infra/portblk-{name}'),
encap_block=dict(aci_class='fvnsEncapBlk', dn='infra/from-{from}-to-{to}'),
vlan_pool=dict(aci_class='fvnsVlanInstP', dn='infra/vlanns-{name}-{allocMode}'),
```

Maybe to be discussed in-person, because also here I may not have the full insights in how this is being used for nested lookups. This is related to #150

**Comment by jmcgill298** [comment]
@dagwieers I've been looking at this the last couple of nights, and the problem is determining the appropriate URL to return. If all parameters are provided, then it is no issue, but what if you want to find all "web" EPGs in Tenant "prod"? The program will either fail when trying to access the ap data because the "ap" parameter was not passed to the module, or trying to access it safely will return unintended results (ap-None). 

There needs to be a way to test if the parameter was passed to the module in order to determine the appropriate URL to return. The current method of the module building a complex parameter out of simpler ones solves that issue. Do you see a way to use formatted strings and identify what parameters are passed to the module?

**Comment by dagwieers** [comment]
You can test if all parameters are available, because an exception wil be raised.

However it would mean we'd have to iterate over the possible alternatives until we find a match related to the available parameters. Not sure how we handle this best though, because some operations have multiple possible URLs.

**Comment by jmcgill298** [comment]
Ya, I thought about try and except, but that seemed like a worse solution imo
